
/* Drop Tables */

DROP TABLE COMMONS CASCADE CONSTRAINTS;
DROP TABLE FILES CASCADE CONSTRAINTS;
DROP TABLE MESSAGES CASCADE CONSTRAINTS;
DROP TABLE POSTS CASCADE CONSTRAINTS;
DROP TABLE RECRUITS CASCADE CONSTRAINTS;
DROP TABLE RESERVATION CASCADE CONSTRAINTS;
DROP TABLE SALE_TRAV CASCADE CONSTRAINTS;
DROP TABLE TRAVEL CASCADE CONSTRAINTS;
DROP TABLE TRAV_COM CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE COMMONS
(
	COMMON_CODE varchar2(5) NOT NULL,
	COMMON_NAME varchar2(30) NOT NULL,
	PRIMARY KEY (COMMON_CODE)
);


CREATE TABLE FILES
(
	COMMON_CODE varchar2(5) NOT NULL,
	CODE varchar2(6) NOT NULL,
	FILE_CODE varchar2(2) NOT NULL,
	FILE_NAME varchar2(90) NOT NULL,
	PRIMARY KEY (COMMON_CODE, CODE, FILE_CODE)
);


CREATE TABLE MEMBERS
(
	MEM_CODE varchar2(7) NOT NULL,
	MEM_ID varchar2(15) NOT NULL UNIQUE,
	MEM_PW varchar2(15) NOT NULL,
	MEM_NAME varchar2(15) NOT NULL,
	MEM_NICK varchar2(21) NOT NULL UNIQUE,
	MEM_PHONE varchar2(11) NOT NULL,
	MEM_EMAIL varchar2(30) NOT NULL UNIQUE,
	MEM_REG_DATE varchar2(8) NOT NULL,
	MEM_POINT number(6) NOT NULL,
	MEM_STATE char NOT NULL,
	GENDER char NOT NULL,
	COMMON_CODE varchar2(5) NOT NULL,
	PRIMARY KEY (MEM_CODE)
);


CREATE TABLE MESSAGES
(
	FROM_MEM_CODE varchar2(7) NOT NULL,
	TO_MEM_CODE varchar2(7) NOT NULL,
	MSG_CODE varchar2(4) NOT NULL,
	MSG_TITLE varchar2(120) NOT NULL,
	MSG_CONT varchar2(4000) NOT NULL,
	MSG_DATE date NOT NULL,
	COMMON_CODE varchar2(5) NOT NULL,
	PRIMARY KEY (FROM_MEM_CODE, TO_MEM_CODE, MSG_CODE)
);


CREATE TABLE POSTS
(
	COMMON_CODE varchar2(5) NOT NULL,
	POST_CODE varchar2(6) NOT NULL,
	MEM_CODE varchar2(7) NOT NULL,
	POST_TITLE varchar2(120) NOT NULL,
	POST_CONT varchar2(4000) NOT NULL,
	POST_DATE date NOT NULL,
	POST_STATE char,
	POST_HIT number(6),
	RE_COMMON_CODE varchar2(5) NOT NULL,
	RE_POST_CODE varchar2(6) NOT NULL,
	RE_STEP number(4) NOT NULL,
	RE_LEVEL number(4) NOT NULL,
	PRIMARY KEY (COMMON_CODE, POST_CODE)
);


CREATE TABLE RECRUITS
(
	COMMON_CODE varchar2(5) NOT NULL,
	RECU_CODE varchar2(3) NOT NULL,
	MEM_CODE varchar2(7) NOT NULL,
	RECU_TITLE varchar2(120) NOT NULL,
	RECU_CONT varchar2(4000) NOT NULL,
	RECU_REG_DATE date NOT NULL,
	RECU_START_DATE varchar2(8) NOT NULL,
	RECU_END_DATE varchar2(8) NOT NULL,
	RECU_DEADLINE varchar2(8) NOT NULL,
	RECU_APPLY_N number(4) NOT NULL,
	RECU_MAX_N number(2) NOT NULL,
	RECU_COMMON_CODE varchar2(5) NOT NULL,
	RECU_HIT number(4) NOT NULL,
	PRIMARY KEY (COMMON_CODE, RECU_CODE)
);


CREATE TABLE RESERVATION
(
	MEM_CODE varchar2(7) NOT NULL,
	RES_CODE varchar2(3) NOT NULL,
	COMMON_CODE varchar2(5) NOT NULL,
	TRAV_CODE varchar2(3) NOT NULL,
	SALE_CODE varchar2(4) NOT NULL,
	PERSON_NUM number(3) NOT NULL,
	RES_DATE date NOT NULL,
	PRIMARY KEY (MEM_CODE, RES_CODE)
);


CREATE TABLE SALE_TRAV
(
	COMMON_CODE varchar2(5) NOT NULL,
	TRAV_CODE varchar2(3) NOT NULL,
	SALE_CODE varchar2(4) NOT NULL,
	START_DAY date NOT NULL,
	END_DAY date NOT NULL,
	SALE_PRICE number(7) NOT NULL,
	CRT_NUM number(3) NOT NULL,
	MAX_NUM number(3) NOT NULL,
	SALE_STATE char NOT NULL,
	PRIMARY KEY (COMMON_CODE, TRAV_CODE, SALE_CODE)
);


CREATE TABLE TRAVEL
(
	COMMON_CODE varchar2(5) NOT NULL,
	TRAV_CODE varchar2(3) NOT NULL,
	COM_CODE varchar2(3) NOT NULL,
	TRAV_NAME varchar2(150) NOT NULL UNIQUE,
	TRAV_PRICE number(7) NOT NULL,
	TRAV_NIGHTS number(2) NOT NULL,
	TRAV_DESC varchar2(4000) NOT NULL,
	TRAV_CONT varchar2(4000) NOT NULL,
	TRAV_REG_DATE date NOT NULL,
	TRAV_STATE char NOT NULL,
	PRIMARY KEY (COMMON_CODE, TRAV_CODE)
);


CREATE TABLE TRAV_COM
(
	COM_CODE varchar2(3) NOT NULL,
	MEM_CODE varchar2(7) NOT NULL,
	COM_NAME varchar2(30) NOT NULL,
	COM_ADDR varchar2(120) NOT NULL,
	OPENING char NOT NULL,
	COM_NUMBER varchar2(12) NOT NULL,
	PRIMARY KEY (COM_CODE)
);



/* Create Foreign Keys */

ALTER TABLE MESSAGES
	ADD FOREIGN KEY (TO_MEM_CODE)
	REFERENCES MEMBERS (MEM_CODE)
;


ALTER TABLE MESSAGES
	ADD FOREIGN KEY (FROM_MEM_CODE)
	REFERENCES MEMBERS (MEM_CODE)
;


ALTER TABLE POSTS
	ADD FOREIGN KEY (MEM_CODE)
	REFERENCES MEMBERS (MEM_CODE)
;


ALTER TABLE RECRUITS
	ADD FOREIGN KEY (MEM_CODE)
	REFERENCES MEMBERS (MEM_CODE)
;


ALTER TABLE RESERVATION
	ADD FOREIGN KEY (MEM_CODE)
	REFERENCES MEMBERS (MEM_CODE)
;


ALTER TABLE TRAV_COM
	ADD FOREIGN KEY (MEM_CODE)
	REFERENCES MEMBERS (MEM_CODE)
;


ALTER TABLE POSTS
	ADD FOREIGN KEY (RE_COMMON_CODE, RE_POST_CODE)
	REFERENCES POSTS (COMMON_CODE, POST_CODE)
;


ALTER TABLE RESERVATION
	ADD FOREIGN KEY (COMMON_CODE, TRAV_CODE, SALE_CODE)
	REFERENCES SALE_TRAV (COMMON_CODE, TRAV_CODE, SALE_CODE)
;


ALTER TABLE SALE_TRAV
	ADD FOREIGN KEY (COMMON_CODE, TRAV_CODE)
	REFERENCES TRAVEL (COMMON_CODE, TRAV_CODE)
;


ALTER TABLE TRAVEL
	ADD FOREIGN KEY (COM_CODE)
	REFERENCES TRAV_COM (COM_CODE)
;



